baseURL = "https://blog.bunch.im/"
languageCode = "en-us"
title = "Creston's Blog"
theme = "natrium"
publishDir = "docs"
enableRobotsTXT = true

[taxonomies]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "About"
    url = "/about/"
   
[params]
    description = "test"